### PR TITLE
pr: issue #6

### PR DESCRIPTION
**Pull request by rithulkamesh**
feat: uses a db using a DIY-ORM
feat: migration script for existing data model
feat: database handled gracefully

### CODE REVIEW

**Comment by polarhive** [comment]
image

!extend 15

**Comment by rithulkamesh** [comment]
@polarhive fixed in the latest commit

**Comment by polarhive** [comment]
will review later

**Comment by polarhive** [comment]
!bounty 350

**Comment by DedLad** [comment]
!bounty 70

**Pull request closed without merging**
